//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATLConveyanceBill.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewWorkLog
    {
        public string Name { get; set; }
        public string EmpId { get; set; }
        public System.DateTime Date { get; set; }
        public string Project { get; set; }
        public string WorkSystem { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
    }
}
